% This test file was generated by Copilot. Validate generated output before use.
classdef RockPaperScissorsTest < matlab.unittest.TestCase
    methods(Test)
        function testTie(testCase)
            p1 = "rock";
            p2 = "rock";
            expectedResult = "Tie";

            actualResult = rockPaperScissors(p1, p2);

            testCase.verifyEqual(actualResult, expectedResult);
        end

        function testPlayer1Wins(testCase)
            p1 = "rock";
            p2 = "scissors";
            expectedResult = "Player 1 wins";

            actualResult = rockPaperScissors(p1, p2);

            testCase.verifyEqual(actualResult, expectedResult);
        end

        function testPlayer2Wins(testCase)
            p1 = "scissors";
            p2 = "rock";
            expectedResult = "Player 2 wins";

            actualResult = rockPaperScissors(p1, p2);

            testCase.verifyEqual(actualResult, expectedResult);
        end

        function testInvalidInput(testCase)
            p1 = "lizard"; % Invalid input
            p2 = "rock";   % Valid input

            testCase.verifyError(@() rockPaperScissors(p1, p2), 'MATLAB:validators:mustBeMember');
        end

        % function testCaseInsensitiveInput(testCase)
        %     p1 = "PAPER";
        %     p2 = "rock";
        %     expectedResult = "Player 2 wins";
        % 
        %     actualResult = rockPaperScissors(p1, p2);
        % 
        %     testCase.verifyEqual(actualResult, expectedResult);
        % end
    end
end